#!/bin/bash
# fix resolve.conf is not correct issue.

set -x

reset_flag=0
file=/etc/resolv.conf
resolv_conf="
#; generated by /sbin/dhclient-script
search jay.org company.com
nameserver 192.168.199.3
nameserver 10.248.2.5
nameserver 10.1.1.5
"

ping my-box1 -c 1 2>&1 | grep -i unknown  && reset_flag=1
ping my-box2 -c 1 2>&1 | grep -i unknown  && reset_flag=1

if [ $reset_flag -eq 1 ]; then
	printf "$resolv_conf" > $file
fi

